version: "3.8"

services:
  www:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./php/www:/var/www/html/
    depends_on:
      - db-server
    networks:
      - default
    environment:
      APACHE_SERVER_NAME: localhost

  db-server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: application-database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db-server
    ports:
      - 8080:80
    links:
      - db-server:db-server
    environment:
      PMA_HOST: db-server
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: toor
    restart: always   
    networks:
      - default

